name: Actualizar precios de referencia

on:
  schedule:
    - cron: '0 22 * * *' # Ejecuta todos los días a las 23:00 (UTC+1)
  workflow_dispatch: # Permite ejecutarlo manualmente

permissions:
  contents: write

jobs:
  actualizar-precios:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script para actualizar precios
        run: node src/leerExcel.js

      - name: Confirmar cambios en preciosReferencia.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add src/preciosReferencia.json
          git commit -m "Actualizar precios de referencia automáticamente"
          git push
