name: Actualizar precios desde Excel

on:
  schedule:
    - cron: '0 22 * * *'  # Ejecutar a las 23:00 en España (UTC+1 → 22h UTC)
  workflow_dispatch:      # Permite ejecución manual desde GitHub

jobs:
  actualizar-precios:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script para actualizar precios
        run: node actualizarPrecios.js

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Hacer commit si hay cambios
        run: |
          git add src/preciosReferencia.json
          if git diff --cached --quiet; then
            echo "No hay cambios en precios, no se hace commit."
          else
            git commit -m "📊 Actualización automática de precios desde Excel"
            git push
          fi
