const xlsx = require('xlsx');
const fs = require('fs');
const path = require('path');

// Ruta del archivo Excel en la raíz del proyecto
const excelPath = path.join(__dirname, 'PreciosP.xlsx');

// Leer el archivo Excel
const workbook = xlsx.readFile(excelPath);
const sheet = workbook.Sheets['3.0TD COMP'];

const periodos = ['P1', 'P2', 'P3', 'P4', 'P5', 'P6'];
const precios = {};

// Extraer los precios para cada periodo
periodos.forEach((periodo, index) => {
  const celda = `N${index + 2}`;
  const valor = sheet[celda] ? Number(sheet[celda].v).toFixed(6) : '0.000000';
  precios[periodo] = valor;
});

// Guardar como JSON
const jsonPath = path.join(__dirname, 'src', 'preciosReferencia.json');
fs.writeFileSync(jsonPath, JSON.stringify(precios, null, 2));

console.log('✅ Precios actualizados correctamente:');
console.log(precios);
